name: Build Docker Image

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download conde-server & font zip file
        run: |
          sudo echo "${{ vars.MINIO_IP }} minio-console.tianshu.com" | sudo tee -a /etc/hosts
          cat /etc/hosts
          wget "${{ vars.CODESEVER_URL }}" -O code-server.tar.gz
          ls -l
          tar -tzvf code-server.tar.gz
          wget "${{ vars.FONT_URL }}" -O chinese.tar.gz
          ls -l
          tar -tzvf chinese.tar.gz
          ls -l
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push latest
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            flowerbirds/yolov8-py3.10-online-cpu:latest
            ghcr.io/flowerbirds/yolov8-py3.10-online-cpu:latest
